Feeding-Thailand/thaifoodbank

functions/post/latestPost.js

Fix the error on latestPost function

---

functions/post/createPost.js

deny multiple posts on same user

---

functions/donate/donate.js
functions/post/closePost.js
functions/post/createPost.js
functions/post/deletePost.js

Stats are maintained:
- `allPosts`: number of unique posts so far
- `activePosts`: number of currently active posts (including deleted/not deleted)
- `closedPosts`: number of currently inactive posts (including deleted/not deleted)
- `deletedPosts`: number of currently deleted posts (including active/inactive)
- `currentPosts`: number of current posts i.e. not yet deleted (including active/inactive)
- `donors`: number of unique donors (resolved uniqueness by `user.uid`)
- `donorsList`: list of donors by `user.uid`

Maintain statistics

---

.github/workflows/functionsCI.yml
functions/.gitignore
functions/donate/donate.js
functions/package-lock.json
functions/package.json
functions/post/contactPost.js
functions/post/createPost.js
functions/post/deletePost.js
functions/post/getPost.js

Maintain donation as a subcollection

---

functions/donate/donate.js
functions/post/getPost.js

- Fixed date format
- Fixed donors variable location in document
- Fixed `getPost` donors count

Minor fixes

---

functions/donate/donate.js

Transactions collection will now collect data upon each donation.

Added transactions collection

---

functions/post/latestPost.js

Yes, I'll do it in other functions as well.

Fix authId on latestPost

---

functions/post/createPost.js
functions/post/getPost.js
functions/posts/oldestPosts.js

Resolved latest features of functions except pagination.

(almost) finalize functions

---

functions/posts/oldestPosts.js

add pagination

---

src/components/helpList.js

Don't mutate array inside state object

Web interface update

---

functions/cleaner/index.js
functions/doDelete.js
functions/index.js
functions/post/deletePost.js

Tried adding Pub/Sub scheduler function to remove inactive posts on 1 month lifetime.

Add scheduler function

---

functions/posts/oldestPosts.js

This requires additional testing.

Fix oldestPosts behavior

---

functions/donate/cancel.js

delete donor fixed

---

functions/helpers/formatImage.js
functions/package-lock.json
functions/package.json
functions/post/createPost.js

Add image resizing and converting to jpg function

---

functions/post/createPost.js

done.
Next step: remove `photos` array from the database and implement with `photosCount` instead.
Required testing.

Fixed same path

---

functions/donate/cancel.js
functions/helpers/formatImage.js
functions/package-lock.json
functions/package.json
functions/post/createPost.js

Update before refactor

---

functions/helpers/doDelete.js
functions/post/createPost.js

[fix] Promise.all wrong syntax

---

functions/helpers/doDelete.js

done. @porames > please check.

Implemented directory deletion

---

functions/post/createPost.js

done. The array data was useless, so I converted into number of photos for cleaner database.

change photos data from array to length

---

src/components/hallOfFame.js
src/pages/help-matcher/faq.js
src/pages/help-matcher/index.js
src/pages/help-matcher/register.js

faq and some other shit
